### ISSUE TITLE
v1.1.68 is missing `filterTOC` property on `IParams_GetDepBoardWithDetails` interface

### ISSUE THREAD

**Issue by rsdev88** [ChronSyn/TSOpenLDB#18]
Hi @ChronSyn 

Following the merge of [this PR](https://github.com/TheTransportLab/TSOpenLDB/pull/17) and the subsequent npm package update to v1.1.68, we should now see the `filterTOC` property on the interface `IParams_GetDepBoardWithDetails`:

https://github.com/TheTransportLab/TSOpenLDB/blob/6b126f640badc1a8769a81d7ddb4697690011bd3/src/interfaces.ts#L168

However, after bumping the package version in my client, it's not there. It seems that there might have been an issue with the package publishing which resulted in the package source not being updated. Could you take a look, please? Thanks in advance.

**Comment by rsdev88** [comment]
@ChronSyn just tagging again in case you didn't receive notifications when this was raised.

**Comment by ChronSyn** [comment]
1.1.69 released with a proposed fix

**Comment by rsdev88** [comment]
> 1.1.69 released with a proposed fix

Awesome, thank you very much :)
